### ISSUE TITLE
Bug: 返回内容过长时无回应

### ISSUE THREAD

**Issue by sxjeru** [limbang/mirai-console-mcmod-plugin#19]
举例：DATA 类型搜索“多功能一体机”，聊天窗口无回复，后台返回下述报错：

```
2022-01-30 22:01:17 E/top.limbang.mirai-console-mcmod-plugin: Exception in coroutine Plugin top.limbang.mirai-console-mcmod-plugin of top.limbang.mirai-console-mcmod-plugin
net.mamoe.mirai.contact.MessageTooLargeException: message([mirai:image:{FBB0D5D2-A730-31C4-73AF-E4FFFBBBC8A9}.png]多功能一体机 (All-in-one Machine)https://www.mcmod...) is too large. Allow up to 50 images or 5000 chars
        at net.mamoe.mirai.internal.contact.UtilKt.verifyLength(util.kt:82)
        at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.transformSpecialMessages$processForwardMessage(SendMessageHandler.kt:304)
        at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.transformSpecialMessages(SendMessageHandler.kt:322)
        at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessage(SendMessageHandler.kt:339)
        at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:168)
        at top.limbang.mirai.mcmod.service.MessageHandle.dataHandle(MessageHandle.kt:63)
        at top.limbang.mirai.mcmod.service.MessageHandle$dataHandle$1.invokeSuspend(MessageHandle.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by jie65535** [comment]
可选的解决方案有：
1. 以多条转发消息组合的方式进行全文发送。
2. 超长消息仅显示部分内容，要查看更多提示跳转原文链接。

我个人更倾向在内容超长时，提示用户跳转到原文阅读。

**Comment by sxjeru** [comment]
赞同方案2。

**Comment by jie65535** [comment]
晚点我提个pr，感谢反馈 : )
