### ISSUE TITLE
Bug搜索等价交换重置版报错

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#20]
![Screenshot_2022-01-31-15-01-41-580_com.microsoft.rdc.android.beta.jpg](https://user-images.githubusercontent.com/49502047/151751731-760e1ba6-03c1-413c-bd71-015c388d6735.jpg)

mirai版本2.10-RC2

**Comment by sxjeru** [comment]
补充日志文本：

```
E/top.limbang.mirai-console-mcmod-plugin: Exception in coroutine Plugin top.limbang.mirai-console-mcmod-plugin of top.limbang.mirai-console-mcmod-plugin
java.io.EOFException: Only 4665 bytes were discarded of 65022 requested
        at kotlinx.io.core.InputKt.discardExact(Input.kt:158)
        at kotlinx.io.core.InputKt.discardExact(Input.kt:168)
        at net.mamoe.mirai.internal.message.ImageDecoderKt.getJPGImageInfo(ImageDecoder.kt:54)
        at net.mamoe.mirai.internal.message.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:155)
        at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$lambda-19$$inlined$runBIO$1.invoke(CoroutineUtils.kt:164)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by limbang** [comment]
![image](https://user-images.githubusercontent.com/6381512/154433290-93cf1fc2-2a01-4fb5-9911-61195820d8a9.png)
上传图片的时候出现的问题
https://docs.fileformat.com/image/jpeg/
<html>
<body>


EOI | 0xFF, 0xD9 | none | End Of Image
-- | -- | -- | --



</body>
</html>
