### ISSUE TITLE
Bug: 疑似不支持WebP图片

### ISSUE THREAD

**Issue by sxjeru** [limbang/mirai-console-mcmod-plugin#25]
以mod类型搜索“车万女仆”，聊天区无回复，后台报以下错误：

```
2022-03-15 16:18:41 E/top.limbang.mirai-console-mcmod-plugin: Exception in coroutine Plugin top.limbang.mirai-console-mcmod-plugin of top.limbang.mirai-console-mcmod-plugin
java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@313b6f38, considering use gif/png/bmp/jpg format. image header: 52 49 46 46 14 EE 01 00 57 45 42 50 56 50 38 4C 07 EE 01 00 2F FF C3 BF 10 CD 30 72 DB 36
        at net.mamoe.mirai.internal.message.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:160)
        at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$lambda-19$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

文件头中可得到以下关键词：
- RIFF
- WEBP VP8L

**Comment by sxjeru** [comment]
已尝试清空图片缓存文件夹，无效。且图片能被正常下载。

问题图片已给出，后缀名应为 webp，不知道为啥百科服务器里存着 jpg。
[1576662810_21294_lICO](https://user-images.githubusercontent.com/20513115/158337265-a7857b18-75d5-4d5d-ac2d-74bc3607322f.jpg)

![image](https://user-images.githubusercontent.com/20513115/158337488-37abd4ab-c835-46b3-9259-ad73ea262d4e.png)

**Comment by limbang** [comment]
到时候看看 正在重构2.0

**Comment by limbang** [comment]
java 默认不支持 webp 已经改成错误提示了
