### ISSUE TITLE
BUG 在搜索部分内容时报错

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#3]
搜索“百科模组bc 查看4时”
`E/top.limbang.mirai-console-mcmod-plugin: Exception in coroutine Plugin top.limbang.mirai-console-mcmod-plugin of top.limbang.mirai-console-mcmod-plugin
java.lang.IllegalStateException: cannot upload group image, failed on all servers.
        at net.mamoe.mirai.internal.network.highway.Highway.uploadResourceBdh(Highway.kt:448)
        at net.mamoe.mirai.internal.network.highway.Highway$uploadResourceBdh$1.invokeSuspend(Highway.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: highway transfer failed, error 83
        at net.mamoe.mirai.internal.network.highway.HighwayKt.sendReceiveHighway(Highway.kt:356)
        at net.mamoe.mirai.internal.network.highway.HighwayKt$sendReceiveHighway$1.invokeSuspend(Highway.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        ... 4 more
        Suppressed: java.lang.IllegalStateException: highway transfer failed, error 83
                ... 8 more
                Suppressed: java.lang.IllegalStateException: highway transfer failed, error 83
                        ... 8 more
                        Suppressed: java.lang.IllegalStateException: highway transfer failed, error 83
                                ... 8 more`
Java:AdoptOpenJDK 11.0.10
mirai2.6.3，2.7M1

**Comment by 502milk** [comment]
已解决
代理问题
