### ISSUE TITLE
搜索模组`猫咪装饰`时报错

### ISSUE THREAD

**Issue by jie65535** [limbang/mirai-console-mcmod-plugin#32]
日志
```java
-> mod 猫咪装饰                
2022-03-30 21:36:49 W/stderr: Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: 'java.lang.String org.jsoup.J
soup.clean(java.lang.String, org.jsoup.safety.Safelist)'                                                                        
2022-03-30 21:36:49 W/stderr:   at top.limbang.mcmod.network.utils.McmodUtilsKt.labelReplacement(McmodUtils.kt:27)              
2022-03-30 21:36:49 W/stderr:   at top.limbang.mcmod.network.converter.ModuleResponseBodyConverter.convert(ModuleResponseBodyCon
verter.kt:59)                                                                                                                   
2022-03-30 21:36:49 W/stderr:   at top.limbang.mcmod.network.converter.ModuleResponseBodyConverter.convert(ModuleResponseBodyCon
verter.kt:22)                                                                                                                   
2022-03-30 21:36:49 W/stderr:   at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
2022-03-30 21:36:49 W/stderr:   at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
2022-03-30 21:36:49 W/stderr:   at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2022-03-30 21:36:49 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-30 21:36:49 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-30 21:36:49 W/stderr:   at java.base/java.lang.Thread.run(Thread.java:829)
```

mcmod对应地址：[猫咪装饰](https://www.mcmod.cn/class/4649.html)

**Comment by limbang** [comment]
暂时无法复现
![6952EA4B-4F58-4F2A-8250-38D977874BCD](https://user-images.githubusercontent.com/6381512/160859497-a10c4025-3568-44ca-a0ed-e97cce069290.png)

```sh
2022-03-30 22:28:38 V/Bot.1157989433: [机器人？(534167901)] limbang(495071565) -> ssm 猫咪装饰
2022-03-30 22:28:49 V/Bot.1157989433: Group(534167901) <- ForwardMessage(preview=[Test: [图片], Test: 主要名称:猫咪装饰\n次要名称:Nekoration, Test: 作者/开发团队:\n[图片]DevBobcorn:Mod作者\n, Test: 原文链接: https://www.mcmod.cn/class/4649.html, Test: 相关链接:\nCurseForge: https://www.curseforge.com/minecraft/mc-mods/nekoration\n码云: https://gitee.com/DevBobcorn/nekoration\n贴吧: 更新直播贴: https://tieba.baidu.com/p/7428888945, Test: [图片]\n注意：本模组仍需改善，且在不断更新。虽然在本模组在作者的服务器上测试时运行稳定，但还是建议备份存档！\n\n\n介绍\nNekoration是一个Forge端的装饰模组，添加了很多装饰性的物品及方块，为玩家建筑时提供更多选择。\n\n\n\n名称来源\n是日语“猫”(ねこ，neko)和“装饰”(decoration)的混成词深受Mojang造词大法熏陶，意为此模组不仅较具观赏价值，而且对猫友好目前体现且仅体现在支持LOLCAT语。\n模组特色\n方块染色\n本模组的大多数方块都可以用原版染料染色，因此你可以把几乎所有东西染成你最喜欢的色调！\n自动连接模型（无需CTM等模组）\n本模组的许多方块都会自动连接模型，如半露木和灯柱。玩家放置后，其会根据相邻的方块自动调整，与之相连。\n绘画\n绘画系统仍需完善不过现在已经能凑活着用了。你可以用调色版调色，然后右键画作，创作出你自己的作品！另外，绘画也支持本地图像(png/jpg)保存/导入功能，所以也可把图像变为画作。\n墙纸\n安装本模组后，你可以用旗帜制作印有相同图案的墙纸(合成方式参考原版给盾牌加图案)。墙纸可以贴在任意墙面上(包括房间的角落)。\n猫咪手册 (生存模式下暂时仅在1.16.5中可通过交易获得)\n如果安装了帕秋莉手册，创造模式"工具"栏(是模组加入的，不是原版的，图标是猫爪爪)中会出现一本红色的手册，讲述了本模组的方方面面奇奇怪怪的设计，比如配方和机制。手册仍在撰写中，随着模组更新会更加详尽。\n语言支持\n本模组目前支持英文，简体中文及LOLCAT，未来可能加入更多语言！\n开发情况\n现已支持1.17.1和1.16.5。两者将同时维护一段时间。等本模组足够完善后，才会重点转向1.17+并进行更多的内容更新，敬请期待！], title=群聊的聊天记录, brief=[聊天记录], source=聊天记录, summary=查看6条转发消息, nodeList=[Node(senderId=1157989433, time=1648650524, senderName=Test, messageChain=[mirai:image:{7468E1D7-3806-A313-32EE-1742CEA1B6FF}.png]), Node(senderId=1157989433, time=1648650525, senderName=Test, messageChain=主要名称:猫咪装饰\n次要名称:Nekoration), Node(senderId=1157989433, time=1648650526, senderName=Test, messageChain=作者/开发团队:\n[mirai:image:{3E999824-E8B4-4D0E-4CBE-34162CB497CE}.jpg]DevBobcorn:Mod作者\n), Node(senderId=1157989433, time=1648650527, senderName=Test, messageChain=原文链接: https://www.mcmod.cn/class/4649.html), Node(senderId=1157989433, time=1648650528, senderName=Test, messageChain=相关链接:\nCurseForge: https://www.curseforge.com/minecraft/mc-mods/nekoration\n码云: https://gitee.com/DevBobcorn/nekoration\n贴吧: 更新直播贴: https://tieba.baidu.com/p/7428888945), Node(senderId=1157989433, time=1648650529, senderName=Test, messageChain=[mirai:image:{9A8CA422-BDFA-9BFB-568A-A77A61994347}.jpg]\n注意：本模组仍需改善，且在不断更新。虽然在本模组在作者的服务器上测试时运行稳定，但还是建议备份存档！\n\n\n介绍\nNekoration是一个Forge端的装饰模组，添加了很多装饰性的物品及方块，为玩家建筑时提供更多选择。\n\n\n\n名称来源\n是日语“猫”(ねこ，neko)和“装饰”(decoration)的混成词深受Mojang造词大法熏陶，意为此模组不仅较具观赏价值，而且对猫友好目前体现且仅体现在支持LOLCAT语。\n模组特色\n方块染色\n本模组的大多数方块都可以用原版染料染色，因此你可以把几乎所有东西染成你最喜欢的色调！\n自动连接模型（无需CTM等模组）\n本模组的许多方块都会自动连接模型，如半露木和灯柱。玩家放置后，其会根据相邻的方块自动调整，与之相连。\n绘画\n绘画系统仍需完善不过现在已经能凑活着用了。你可以用调色版调色，然后右键画作，创作出你自己的作品！另外，绘画也支持本地图像(png/jpg)保存/导入功能，所以也可把图像变为画作。\n墙纸\n安装本模组后，你可以用旗帜制作印有相同图案的墙纸(合成方式参考原版给盾牌加图案)。墙纸可以贴在任意墙面上(包括房间的角落)。\n猫咪手册 (生存模式下暂时仅在1.16.5中可通过交易获得)\n如果安装了帕秋莉手册，创造模式"工具"栏(是模组加入的，不是原版的，图标是猫爪爪)中会出现一本红色的手册，讲述了本模组的方方面面奇奇怪怪的设计，比如配方和机制。手册仍在撰写中，随着模组更新会更加详尽。\n语言支持\n本模组目前支持英文，简体中文及LOLCAT，未来可能加入更多语言！\n开发情况\n现已支持1.17.1和1.16.5。两者将同时维护一段时间。等本模组足够完善后，才会重点转向1.17+并进行更多的内容更新，敬请期待！)])
```

**Comment by jie65535** [comment]
搜索所有mod，展示mod详情的时候都会出现该问题。跟搜索的内容无关。
怀疑跟jsoup版本有关。因为它报告的错误是`java.lang.NoSuchMethodError: 'java.lang.String org.jsoup.Jsoup.clean(java.lang.String, org.jsoup.safety.Safelist)'`

**Comment by limbang** [comment]
你是什么环境运行的  我尝试下一样的环境试试 我不报错也不好找问题

**Comment by jie65535** [comment]
额，我是拉dev分支然后运行`buildPlugin`任务编译的。
系统是树莓派4B，我还有其它插件也使用了Jsoup作为依赖。
我先看看它们的版本是不是不一样。更新一下试试。

**Comment by limbang** [comment]
Jsoup 的版本我确实更新过 `implementation("org.jsoup:jsoup:1.14.3")`

**Comment by jie65535** [comment]
我另一个插件用的是`implementation("org.jsoup:jsoup:1.13.1")`，我升级一下试试

**Comment by jie65535** [comment]
用是可以用了，但是上来就谈了几个警告
```java
WARNING: An illegal reflective access operation has occurred                                                                  
WARNING: Illegal reflective access by retrofit2.Platform (file:/home/pi/Mirai/plugins/mirai-console-mcmod-plugin-2.0.5.mirai.jar
) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)                                                     
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform                                                
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                           
WARNING: All illegal access operations will be denied in a future release
```

**Comment by limbang** [comment]
正常的。反射的警告 我记得改啥配置可以取消显示的
